version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    milestone: 4
    asignees:
      - "Morgan-Phoenix"
    labels:
      - "dependencies"
    
