# .readthedocs.yaml - Configuration file for readthedocs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

# Version (required)
version: 2

# Sphinx Configuration
sphinx:
    configuration: docs/source/conf.py

# Formats for build
formats:
    - htmlzip
    - pdf
    - epub

# Python configuration and requirements
python:
    version: 3.8
    install:
        - requirements: docs/requirements.txt
