blank_issues_enabled: true

contact_links:
  - name: Question
    url: https://github.com/play4Tutorials/py_everything/discussions/categories/q-a
    about: Have a question? Find your answer on GitHub Discussions!

  - name: Documentation
    url: http://py_everything.readthedocs.io/
    about: Can't figure out something? Check out our Documentation!
