blank_issues_enabled: true

contact_links:
  - name: Question
    url: https://stackoverflow.com/questions/tagged/py-everything
    about: Have a question? Find your answer here!

  - name: Documentation
    url: http://py_everything.readthedocs.io/
    about: Can't figure out something? Check out our Documentation!
