name: Code Coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        pip install coverage playsound enrocrypt pip --upgrade
        cd tests/
        coverage run test_py_everything.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        env_vars: OS,PYTHON
        fail_ci_if_error: true
